x-vippet: &vippet
  image: docker.io/intel/vippet-app:${DOCKER_TAG}
  build:
    context: .
    dockerfile: Dockerfile.vippet
  ports:
    - "7860:7860"
  healthcheck:
    test: ["CMD", "curl", "--fail", "--silent", "--show-error", "--output", "/dev/null", "http://localhost:7860/"]
    interval: 30s
    timeout: 10s
    retries: 5
  depends_on:
    models:
      condition: service_completed_successfully
  restart: on-failure:5
  environment:
    GST_DEBUG: "1"
    TZ: America/Los_Angeles
    PIPELINE: smartnvr
  env_file:
    - path: '.public_models_env'
      required: false
  volumes:
    - collector-signals:/home/dlstreamer/vippet/.collector-signals
    - ./models:/home/dlstreamer/vippet/models

services:
  models:
    image: intel/dlstreamer:2025.1.2-ubuntu24
    container_name: models
    volumes:
      - ./models/:/output
      - ./models.sh:/home/dlstreamer/models.sh
    environment:
      - MODELS_PATH=/output/
    env_file:
      - path: '.public_models_env'
        required: false
    command: './models.sh'
    restart: on-failure:5
  vippet-cpu:
    <<: *vippet
    container_name: vippet-cpu
    profiles: [cpu]
  vippet-gpu:
    <<: *vippet
    container_name: vippet-gpu
    group_add:
     - ${RENDER_GROUP_ID}
    devices:
      - "/dev/dri:/dev/dri"
    profiles: [gpu]
  vippet-npu:
    <<: *vippet
    container_name: vippet-npu
    group_add:
     - ${RENDER_GROUP_ID}
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/accel:/dev/accel"
    profiles: [npu]
  collector:
    image: docker.io/intel/vippet-collector:${DOCKER_TAG}
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: collector
    privileged: true
    devices:
      - "/sys:/sys"
      - "/dev:/dev"
      - "/run:/run"
      - "/proc:/proc"
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - "collector-signals:/app/.collector-signals"
    restart: on-failure:5
  videogenerator:
    profiles: [do-not-start]
    image: docker.io/intel/vippet-videogenerator:${DOCKER_TAG}
    build:
      context: video_generator
      dockerfile: Dockerfile
    container_name: videogenerator
    volumes:
      - "./videos:/usr/src/app/output"
      - "./video_generator/config.json:/usr/src/app/config.json"
      - "./video_generator/background.gif:/usr/src/app/background.gif"
      - "./video_generator/images:/usr/src/app/images"

volumes:
  collector-signals:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
