apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatqna-core-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatqna-core-ui
  template:
    metadata:
      labels:
        app: chatqna-core-ui
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: chatqna-core-ui
          image: "{{ .Values.image.registry }}chatqna-ui:{{ .Values.image.uiTag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: http_proxy
              value: "{{ .Values.global.http_proxy }}"
            - name: https_proxy
              value: "{{ .Values.global.https_proxy }}"
            - name: no_proxy
              value: "{{ .Values.global.no_proxy }}"
            - name: APP_BACKEND_URL
              value: "{{ .Values.global.app_backend_url }}"
          ports:
            - containerPort: 8102
