name: "[DLS] [U22/24] Build dev imgs and run Unit Tests"
run-name: "[DLS] [U22/24] Build dev imgs and run Unit Tests(by ${{ github.actor }})"
on:
  workflow_call:
  workflow_dispatch:
permissions: {}
env:
  MODELS_PATH: "/home/runner/models"
  VIDEO_INPUTS_PATH: "/home/runner/videos"

jobs:
  build:
    name: Build dev ${{ matrix.ubuntu_version }} imgs and run unit
    runs-on: [dls, ubuntu]
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - path_dockerfile: ./edge-ai-libraries-repo/libraries/dl-streamer/docker/ubuntu/ubuntu22.Dockerfile
            ubuntu_version: ubuntu22
          - path_dockerfile: ./edge-ai-libraries-repo/libraries/dl-streamer/docker/ubuntu/ubuntu24.Dockerfile
            ubuntu_version: ubuntu24
    steps:
    - name: Clean before
      run: |
        sudo rm -rf edge-ai-libraries-repo

    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      with:
        path: edge-ai-libraries-repo
        persist-credentials: false

    - name: Init submodules
      run: |
        cd edge-ai-libraries-repo
        git submodule update --init libraries/dl-streamer/thirdparty/spdlog
        git submodule update --init libraries/dl-streamer/thirdparty/googletest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #3.10.0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build dev debug img with cache from GHCR
      env:
        dev_debug_img: ghcr.io/${{ github.repository }}/dev-debug-img-${{ matrix.ubuntu_version }}:${{ github.sha }}
        dev_debug_img_cached: ghcr.io/${{ github.repository }}/dev-debug-img-${{ matrix.ubuntu_version }}:buildcache
      run: |
        docker buildx build \
          --load \
          --target dlstreamer-dev \
          --tag "${dev_debug_img}" \
          --cache-from="${dev_debug_img_cached}" \
          --build-arg BUILD_ARG=Debug \
          -f ${{ matrix.path_dockerfile }} \
          ./edge-ai-libraries-repo/libraries/dl-streamer

    # ====================================================== UNIT TESTS ============================================================

    - name: Print system information
      run: |
        echo "## System information" >> $GITHUB_STEP_SUMMARY
        echo "Runner name: ${{ runner.name }}" >> $GITHUB_STEP_SUMMARY
        echo "OS Type: $(uname -o)" >> $GITHUB_STEP_SUMMARY
        echo "OS version: $(. /etc/os-release && echo "$PRETTY_NAME")" >> $GITHUB_STEP_SUMMARY
        echo "Kernel Version: $(uname -r)" >> $GITHUB_STEP_SUMMARY
        echo "CPU Name: $(lscpu | grep 'Model name' | sed 's/Model name:[ \t]*//')" >> $GITHUB_STEP_SUMMARY

    - name: Check models
      run: |
        echo "## Basic checks" >> $GITHUB_STEP_SUMMARY
        if [ -d "${{ env.MODELS_PATH }}" ] && [ "$(ls -A "${{ env.MODELS_PATH }}")" ]; then
          echo "Models: found ✅" >> $GITHUB_STEP_SUMMARY
          ls -A "${{ env.MODELS_PATH }}"
        else
          echo "Models: folder not found or it is empty ❌" >> $GITHUB_STEP_SUMMARY
          ls -A "${{ env.MODELS_PATH }}"
          exit 1
        fi

    - name: Check videos
      run: |
        if [ -d "${{ env.VIDEO_INPUTS_PATH }}" ] && [ "$(ls -A "${{ env.VIDEO_INPUTS_PATH }}")" ]; then
          echo "Tests input videos: found ✅" >> $GITHUB_STEP_SUMMARY
        else
          echo "Tests input videos: folder not found or it is empty ❌" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

    - name: Create test results folder
      env:
        RESULTS_DIR: test-results
      run: |
        mkdir -p ${RESULTS_DIR}
        chmod -R 777 ${RESULTS_DIR}

    - name: Run tests
      id: run-tests
      env:
        dev_debug_img: ghcr.io/${{ github.repository }}/dev-debug-img-${{ matrix.ubuntu_version }}:${{ github.sha }}
        MAPPED_MODELS_PATH: /home/dlstreamer/models
        MAPPED_RESULTS_DIR: /home/dlstreamer/test-results
        MAPPED_VIDEO_EXAMPLES_DIR: /home/dlstreamer/video-examples
        RESULTS_DIR: test-results
      run: |
        docker run --device /dev/dri --rm \
          --group-add=$(stat -c "%g" /dev/dri/render*) \
          -v ${{ env.VIDEO_INPUTS_PATH }}:${MAPPED_VIDEO_EXAMPLES_DIR} \
          -v ${{ env.MODELS_PATH }}:${MAPPED_MODELS_PATH} \
          -v $PWD/${RESULTS_DIR}:${MAPPED_RESULTS_DIR}        \
          -v $PWD/edge-ai-libraries-repo/libraries/dl-streamer/tests/scripts:/home/dlstreamer/dlstreamer/scripts  \
          -v $PWD/edge-ai-libraries-repo/libraries/dl-streamer/tests/unit_tests:/home/dlstreamer/dlstreamer/tests \
          -e VIDEO_EXAMPLES_DIR=${MAPPED_VIDEO_EXAMPLES_DIR}  \
          -w /home/dlstreamer/dlstreamer  \
          -e MODELS_PATH=${MAPPED_MODELS_PATH} \
          -e MODELS_PROC_PATH=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc \
          ${dev_debug_img} \
          scripts/run_unit_tests.sh "" "" ${MAPPED_RESULTS_DIR}

    #this script creates output file called unit_test_summary.txt
    - name: Run python script to get Unit Test results
      env:
        RESULTS_DIR: test-results
      run: python3 edge-ai-libraries-repo/libraries/dl-streamer/tests/scripts/unit_test_results.py $PWD/${RESULTS_DIR}

    - name: Add test summary to job summary
      if: always ()
      env:
        RESULTS_DIR: test-results
      run: |
        echo "## Test Summary for Unit Tests on TGL" >> $GITHUB_STEP_SUMMARY
        cat $PWD/${RESULTS_DIR}/unit_test_summary.txt >> $GITHUB_STEP_SUMMARY

    - name: Upload test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #4.6.2
      if: always ()
      env:
        RESULTS_DIR: test-results
      with:
        name: unit_tests_tgl_${{ matrix.ubuntu_version }}
        path: ${{ env.RESULTS_DIR }}/*.xml

    - name: Clean up
      if: always ()
      env:
        RESULTS_DIR: test-results
      run: sudo rm -rf ${RESULTS_DIR} edge-ai-libraries-repo
